name: Show grep error in workflow # worflow name

on: [push] # event

jobs:
  show-problem:
    runs-on: ubuntu-latest # runner version

    steps:
    - name: create file
      run: echo 'a1 , a2 , a3' > a.txt

    - name: simple grep found
      run: |
        grep a1 a.txt
        echo 'after grep found'

    - name: simple grep not found
      run: | 
        grep a4 a.txt  
        echo 'after grep not found'